### ISSUE TITLE
Create examples page

### ISSUE THREAD

**Issue by mattwondra** [apartmenttherapy/react-pinboard#4]

**Comment by sunsheeppoplar** [comment]
Anything y'all had in mind as far as making an acceptable PR for this issue? Been looking for projects to contribute to and really admire the work y'all do!

**Comment by mattwondra** [comment]
Hi @sunsheeppoplar! Thanks for the comment and interest!

I don't think we have super strong opinions about what a first-run at an examples page should look like. Top priority would be to cover basic use cases showing a code sample next to a live rendering of that code. So at the very minimum, something like a list of images using some media queries to adjust the column count with browser size.

Beyond that, I'd love to see more advanced features shown off as well, such as:
- Examples of mixed-media items (e.g. a Pinboard that combines plain old `<img>`s alongside decorated pull-quotes, alongside interactive React widgets...)
- A clear example of how item ordering works when items have different heights, especially when using mixed media (as images get narrower their height shrinks — as text gets narrower, its height grows)
- An interactive playground where you can adjust the props on-the-fly, including the number and order of children

But really — anything that shows the basic use case better than pointing at a blog post where it's used (the current solution) would just be fantastic.

I hope this helps, and if you're interested in contributing in this way I'd be very appreciative! Thanks!
